## Table of Contents # Numpy Master for ( Data analysis, machine learning and AI )

<span id="0"></span>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ol>
    <li><a href="#1">Numpy Array</a></li> 
     <li><a href="#2">Indexing & Slicing</a></li> 
    <li><a href="#3">Single & Scaler Vector Operation</a></li> 
    <li><a href="#4">Vector-vector element wise operator</a></li> 
    <li><a href="#5">Vector-vector dot product</a></li> 
</ol>
</div>
<hr>


<a id="1"></a>
### 1. Vector Creation  Numpy Array 
<a href="#0">Click here to Go to Table of content</a>

In [22]:
def print_numpy_array(headline,arr):
    print(headline)
    print(f"array :   a = {arr}, a shape = {arr.shape}, a data type = {arr.dtype}",'\n')

In [55]:
import numpy as np

a = np.zeros(4) 
print_numpy_array("# passing singluar dimention",a)


a = np.zeros((4,)) 
print_numpy_array('# passing tuple as dimention (n,) -> 1-D , (n,n) -> 2 -D etc', a)



a = np.arange(8.0).reshape((2,4))
a = np.zeros_like(a)
print_numpy_array('#create zero array, copy shape and data type of passed array', a)


a = np.random.random_sample((4,)) 
print_numpy_array('# all random samples has values less than one',a)


a = np.arange(4)
print_numpy_array('# range you can pass integer or float , Not taking dimention as input, Create 1-D array', a) 


a = np.random.rand(4) 
print_numpy_array('# passing the value not as dimention ( always create 1-D Array )', a)


a = np.array([1,4,7,9]) 
print_numpy_array('# passing data manually to create an array', a)

a = np.array([[1,4,7,9],[4,5,6,7]]) 
print_numpy_array('',a)

a = np.array([1.0,4,7,9]) 
print_numpy_array('# passing data manualy but list contdain different datatypes', a)


# passing singluar dimention
array :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64 

# passing tuple as dimention (n,) -> 1-D , (n,n) -> 2 -D etc
array :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64 

#create zero array, copy shape and data type of passed array
array :   a = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]], a shape = (2, 4), a data type = float64 

# all random samples has values less than one
array :   a = [0.41783454 0.53671084 0.19721356 0.26810967], a shape = (4,), a data type = float64 

# range you can pass integer or float , Not taking dimention as input, Create 1-D array
array :   a = [0 1 2 3], a shape = (4,), a data type = int64 

# passing the value not as dimention ( always create 1-D Array )
array :   a = [0.5669563  0.36607953 0.12254939 0.41590761], a shape = (4,), a data type = float64 

# passing data manually to create an array
array :   a = [1 4 7 9], a shape = (4,), a data type = int64 


array :   a = [[1 4 7 9]
 [4 5 6 7]], a shape = (2, 

<a id="2"></a>
### 2. Indexing and Slicing
- Indexing : getting single element from an array
- Slicing : getting subset of element from an array `(start-include:stop-depend on step:step-1 means consequitive)`

<a href="#0">Click here to Go to Table of content</a>

In [31]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)
print(a[0],a[-10], a[9], a[-1])

try:
     c = a[10]
except Exception as e:
    print("The error message you will see is")
    print(e)

    
    
#access 5 consecutive elements (start:stop:step) ( start and end are included )
c = a[2:7:1];  
print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     
print("a[2:7:2] = ", c)

# access all elements index 3 and above ( start index include )
c = a[3:];        
print("a[3:]    = ", c)

# access all elements below index 3 ( end endex is not included )
c = a[:3];        
print("a[:3]    = ", c)

# access all elements
c = a[:];         
print("a[:]     = ", c)

[0 1 2 3 4 5 6 7 8 9]
0 0 9 9
The error message you will see is
index 10 is out of bounds for axis 0 with size 10
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="3"></a>
### 3. Single & Scaler Vector Operation
<a href="#0">Click here to Go to Table of content</a>

In [34]:
# Vector index operator on 1-D vectors
a = np.arange(10)
print(a)

#Negative vector
b = -a
print(b)

# sum of all elements
b = np.sum(a)
print(b)


#mean of all elements ( why the mean is 45 ) 
b = np.mean(a)
print(b)

#power to 2 of all elemnts
b= a**2
print(b)

#multiplie each element by 3
b = a*2
print(b)

#add one to all elements
b = a +1
print(b)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
45
4.5
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  2  3  4  5  6  7  8  9 10]


<a name="4"></a>
### 4. Vector - 2 element wise operations
<a href="#0">Click here to Go to Table of content</a>

In [39]:
# Pair wise sum
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
print(a +b)

#pair wise multiplication
print(a*b)



[ 3  5  7  9 11]
[ 2  6 12 20 30]


<a name="5"></a>
### 5. Vector Vector dot product
<a href="#0">Click here to Go to Table of content</a>

In [45]:
import numpy as np
import time
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [46]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [47]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


#### Vector speed test

In [49]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 3.8698 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2510.8080 ms 


<a name="6"></a>
### 6. Matrix Properties
<a href="#0">Click here to Go to Table of content</a>

- AB != BA ( Matrix multiplication is not commutative 
- AI = IA = A ( I is identity matrix , Multipying an identity matrix is the matrix itself

<a name="7"></a>
### 7. Linespace
<a href="#0">Click here to Go to Table of content</a>

- np.linspace(start, stop, num_points,endpoint=False) 
- include both start and stop poing 
- includes evenly space num_points
- Used heavily for visualization and parameter sweeps

In [51]:
import numpy as np
np.linspace(-100, 500, 50)

array([-100.        ,  -87.75510204,  -75.51020408,  -63.26530612,
        -51.02040816,  -38.7755102 ,  -26.53061224,  -14.28571429,
         -2.04081633,   10.20408163,   22.44897959,   34.69387755,
         46.93877551,   59.18367347,   71.42857143,   83.67346939,
         95.91836735,  108.16326531,  120.40816327,  132.65306122,
        144.89795918,  157.14285714,  169.3877551 ,  181.63265306,
        193.87755102,  206.12244898,  218.36734694,  230.6122449 ,
        242.85714286,  255.10204082,  267.34693878,  279.59183673,
        291.83673469,  304.08163265,  316.32653061,  328.57142857,
        340.81632653,  353.06122449,  365.30612245,  377.55102041,
        389.79591837,  402.04081633,  414.28571429,  426.53061224,
        438.7755102 ,  451.02040816,  463.26530612,  475.51020408,
        487.75510204,  500.        ])

<a name="8"></a>
### 7. Mash grid
<a href="#0">Click here to Go to Table of content</a>

- create all possible pairs of two 1-D Array
- It turns 1D vectors into 2D coordinate matrices.
- Used in ML to plot the cost function for every pair of w,b

In [58]:
w_vals = np.array([1,2,3])
b_vals = np.array([5,6])

# with these two array, you can create all the pairs of x and y
W, B = np.meshgrid(w_vals, b_vals)
print(W,B)

[[1 2 3]
 [1 2 3]] [[5 5 5]
 [6 6 6]]


#### Old content

In [13]:
onesArray = np.diag([1,2,3])


In [14]:
onesArray


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

##### Slicing of the numpy array

In [53]:
# First Row
onesArray[:, 0]

array([1, 0, 0])

In [54]:
# second Row
onesArray[:, 1]

array([0, 2, 0])

In [55]:
#Third Row
onesArray[:, 2]

array([0, 0, 3])

In [58]:
# First Column
onesArray[:, 0:1]

array([[1],
       [0],
       [0]])

In [59]:
# Second column
onesArray[:, 1:2]

array([[0],
       [2],
       [0]])

In [61]:
# Third Column
onesArray[:, 2:3]

array([[0],
       [0],
       [3]])

array([[1, 0, 0]])

array([[1, 0, 0]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[0, 0],
       [2, 0],
       [0, 3]])

array([[0],
       [0],
       [3]])

In [33]:
onesArray[:, :1

array([[1],
       [0],
       [0]])

In [34]:
onesArray[:, :2]

array([[1, 0],
       [0, 2],
       [0, 0]])

In [36]:
onesArray[:, 1:2]

array([[0],
       [2],
       [0]])

In [37]:
onesArray[:, 2:3]

array([[0],
       [0],
       [3]])

In [35]:
onesArray[:, :3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])